### dog breed fetch from API
GET https://api.thedogapi.com/v1/breeds/search?q=Akita
Headers:
  x-api-key: live_YnK8hERadS4Aj9jL4US6eso0uFN3hTAvB0hTA1n3hmXlcHZGkp0LuAPo5KLxA9RN

### add Dog to User
POST http://localhost:8080/ca2_Personal/api/dog/addDogToUser/user
Content-Type: application/json

{
  "id": 6,
  "name": "Akita",
  "life_span": "10 - 14 years",
  "weight": {
    "imperial": "65 - 115",
    "metric": "29 - 52"
  }
}

### remove Dog from User
DELETE http://localhost:8080/ca2_Personal/api/dog/removeDogFromUser/user/4
Content-Type: application/json